name: Snapshot
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]
    tags-ignore: ["v*"]
jobs:
  formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
      - name: Run scalafmt
        run: sbt scalafmtCheck

  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
      - name: Run tests
        run: sbt contracts/test

  snapshot:
    name: Publish snapshot to Sonatype
    needs: [build, formatting]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
      - name: Install Z3 prover
        run: curl -fsSL https://github.com/Z3Prover/z3/releases/download/z3-4.8.7/z3-4.8.7-x64-ubuntu-16.04.zip -o z3-4.8.7-x64-ubuntu-16.04.zip; unzip -j z3-4.8.7-x64-ubuntu-16.04.zip -d z3_downloaded; export PATH=$PATH:$(pwd)/z3_downloaded; z3 --version;
      - name: Publish contracts snapshot ${{ github.ref }}
        run: sbt contracts/publish
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

